// 조선 후기(1700~1876) 키워드·디테일 카드 — Level 2 매칭 테스트용 데이터 풀.
// 새 통합 스키마(type / kind / tags 명시) 적용.
//
// 이 파일의 카드들은 sample_joseon.js(영조/정조/흥선대원군 등 keyword)와
// data.js의 기존 조선 후기 사건 카드들(균역법 시행/신유박해/홍경래의 난 등 default keyword)과
// 함께 조선 후기 영역의 데이터 풀을 구성.
//
// 신규 keyword: 4개 (왕 3, 사상 1)
// 신규 detail: 22개 (영조 3 / 정조 5 / 세도정치기 5 / 흥선대원군 4 / 양요 4 / 동학 1)

const LATE_JOSEON_KEYWORDS = [
  // ===== 왕 (신규) =====
  {
    type: '왕', kind: 'keyword',
    title: '조선 순조',
    description: '11세 즉위로 안동 김씨 세도정치 시작. 신유박해·홍경래의 난을 겪음',
    startYear: 1800, endYear: 1834,
    difficulty: 3,
    era: '조선시대',
    tags: ['조선', '세도정치', '신유박해', '홍경래의 난'],
  },
  {
    type: '왕', kind: 'keyword',
    title: '조선 철종',
    description: '강화도령으로 불린 평민 출신 왕. 임술농민봉기·삼정 문란이 폭발한 시기',
    startYear: 1849, endYear: 1863,
    difficulty: 4,
    era: '조선시대',
    tags: ['조선', '세도정치', '임술농민봉기', '삼정 문란', '동학'],
  },
  {
    type: '왕', kind: 'keyword',
    title: '조선 고종',
    description: '12세 즉위로 흥선대원군 섭정. 후에 친정·대한제국 수립. 개항·근대 격변의 임금',
    startYear: 1863, endYear: 1907,
    difficulty: 1,
    era: '조선시대',
    tags: ['조선', '흥선대원군', '강화도 조약', '대한제국'],
  },

  // ===== 사상/종교 (신규) =====
  {
    type: '문화', kind: 'keyword',
    title: '동학',
    description: '1860년 최제우가 창시한 민중 종교·사상. 인내천 사상, 후에 동학농민운동의 기반',
    startYear: 1860, endYear: 1860,
    difficulty: 3,
    era: '조선시대',
    tags: ['조선', '조선 철종', '최제우', '인내천'],
  },

  // ===== 다른 디테일에서 tag로 참조되지만 키워드 미등록이던 항목 일괄 등록 =====
  // 제도·현상
  {
    type: '제도', kind: 'keyword',
    title: '삼정 문란',
    description: '세도정치기 전정·군정·환곡 등 조세 행정의 부패가 극에 달한 현상',
    startYear: 1800, endYear: 1862,
    difficulty: 2, era: '조선시대',
    tags: ['조선 철종', '임술농민봉기'],
  },
  {
    type: '시대', kind: 'keyword',
    title: '세도정치',
    description: '순조~철종 60여 년간 안동 김씨·풍양 조씨 등 외척 가문이 권력 독점',
    startYear: 1800, endYear: 1863,
    difficulty: 2, era: '조선시대',
    tags: ['조선 순조', '조선 헌종', '조선 철종'],
  },
  {
    type: '제도', kind: 'keyword',
    title: '통상수교거부',
    description: '흥선대원군의 외세 통상 거부 정책. 척화비 건립으로 상징',
    startYear: 1863, endYear: 1873,
    difficulty: 2, era: '조선시대',
    tags: ['흥선대원군', '병인양요', '신미양요'],
  },
  // 왕
  {
    type: '왕', kind: 'keyword',
    title: '조선 헌종',
    description: '8세 즉위 후 풍양 조씨 세도정치. 천주교 박해(기해박해) 시기',
    startYear: 1834, endYear: 1849,
    difficulty: 3, era: '조선시대',
    tags: ['조선', '세도정치'],
  },
  // 인물
  {
    type: '인물', kind: 'keyword',
    title: '장영실',
    description: '세종 때 천문기구(혼천의·앙부일구)와 측우기를 제작한 과학자',
    startYear: 1390, endYear: 1450,
    difficulty: 2, era: '조선시대',
    tags: ['조선 세종', '측우기'],
  },
  {
    type: '인물', kind: 'keyword',
    title: '사육신',
    description: '단종 복위를 도모하다 세조에게 처형된 성삼문·박팽년 등 여섯 신하',
    startYear: 1456, endYear: 1456,
    difficulty: 3, era: '조선시대',
    tags: ['조선 세조', '계유정난'],
  },
  {
    type: '인물', kind: 'keyword',
    title: '곽재우',
    description: '임진왜란 때 의병을 일으킨 홍의장군',
    startYear: 1552, endYear: 1617,
    difficulty: 3, era: '조선시대',
    tags: ['임진왜란', '조선 선조'],
  },
  {
    type: '인물', kind: 'keyword',
    title: '최제우',
    description: '동학 창시자. 인내천 사상 주창',
    startYear: 1824, endYear: 1864,
    difficulty: 2, era: '조선시대',
    tags: ['동학', '조선 철종'],
  },
  {
    type: '인물', kind: 'keyword',
    title: '양헌수',
    description: '병인양요 때 정족산성에서 프랑스군을 격퇴한 장수',
    startYear: 1816, endYear: 1888,
    difficulty: 4, era: '조선시대',
    tags: ['병인양요', '흥선대원군'],
  },
  {
    type: '인물', kind: 'keyword',
    title: '어재연',
    description: '신미양요 때 광성보 전투에서 전사한 장수',
    startYear: 1823, endYear: 1871,
    difficulty: 4, era: '조선시대',
    tags: ['신미양요', '흥선대원군'],
  },
];

const LATE_JOSEON_DETAILS = [
  // ===== 조선 영조 detail =====
  {
    id: '탕평비_건립',
    type: '유물', kind: 'detail',
    title: '탕평비 건립',
    description: '조선 영조가 성균관 앞에 세운 비석으로 탕평책의 의지를 표명',
    startYear: 1742, endYear: 1742,
    difficulty: 4,
    era: '조선시대',
    tags: ['조선 영조', '영조 탕평책', '성균관'],
  },
  {
    id: '속대전_편찬',
    type: '사건', kind: 'detail',
    title: '속대전 편찬',
    description: '조선 영조 때 경국대전 이후 변화된 법을 정리한 법전을 편찬',
    startYear: 1746, endYear: 1746,
    difficulty: 4,
    era: '조선시대',
    tags: ['조선 영조'],
  },
  {
    id: '청계천_준설',
    type: '사건', kind: 'detail',
    title: '청계천 준설',
    description: '조선 영조가 한양 도성 안 청계천의 토사를 걷어내는 대규모 토목 사업을 시행',
    startYear: 1760, endYear: 1760,
    difficulty: 5,
    era: '조선시대',
    tags: ['조선 영조'],
  },

  // ===== 조선 정조 detail =====
  {
    id: '신해통공',
    type: '제도', kind: 'detail',
    title: '신해통공',
    description: '조선 정조가 시전 상인의 금난전권을 폐지해 사상(私商) 활동을 허용',
    startYear: 1791, endYear: 1791,
    difficulty: 4,
    era: '조선시대',
    tags: ['조선 정조'],
  },
  {
    id: '초계문신제',
    type: '제도', kind: 'detail',
    title: '초계문신제',
    description: '조선 정조가 젊은 문신을 규장각에서 재교육한 인재 양성 제도',
    startYear: 1781, endYear: 1781,
    difficulty: 4,
    era: '조선시대',
    tags: ['조선 정조', '규장각'],
  },
  {
    id: '대전통편_편찬',
    type: '사건', kind: 'detail',
    title: '대전통편 편찬',
    description: '조선 정조가 경국대전·속대전을 통합 정리한 법전을 편찬',
    startYear: 1785, endYear: 1785,
    difficulty: 5,
    era: '조선시대',
    tags: ['조선 정조'],
  },
  {
    id: '거중기',
    type: '유물', kind: 'detail',
    title: '거중기',
    description: '조선 정조 시기 정약용이 만든 도르래 활용 기중기 — 수원 화성 축조에 활용',
    startYear: 1792, endYear: 1792,
    difficulty: 3,
    era: '조선시대',
    tags: ['조선 정조', '정약용', '수원 화성'],
  },
  {
    id: '화성성역의궤_편찬',
    type: '유물', kind: 'detail',
    title: '화성성역의궤 편찬',
    description: '조선 정조 시기 수원 화성 축조 전 과정을 그림과 함께 기록한 의궤',
    startYear: 1801, endYear: 1801,
    difficulty: 5,
    era: '조선시대',
    tags: ['조선 정조', '수원 화성'],
  },

  // ===== 세도정치기 (순조~철종) detail =====
  {
    id: '세도정치',
    type: '제도', kind: 'detail',
    title: '세도정치',
    description: '조선 순조 즉위 후 외척 안동 김씨·풍양 조씨가 권력을 독점한 정치 형태',
    startYear: 1800, endYear: 1863,
    difficulty: 3,
    era: '조선시대',
    tags: ['조선 순조', '조선 헌종', '조선 철종', '세도정치 시작'],
  },
  {
    id: '비변사_강화',
    type: '기관', kind: 'detail',
    title: '비변사 강화',
    description: '세도정치 시기 비변사가 의정부를 무력화시키며 국정 최고 기구로 부상',
    startYear: 1800, endYear: 1863,
    difficulty: 4,
    era: '조선시대',
    tags: ['세도정치', '조선 순조', '조선 철종'],
  },
  {
    id: '최제우_동학_창시',
    type: '사건', kind: 'detail',
    title: '최제우의 동학 창시',
    description: '경주 출신 최제우가 동학을 창시 — 인내천·시천주 사상으로 민중 호응',
    startYear: 1860, endYear: 1860,
    difficulty: 3,
    era: '조선시대',
    tags: ['동학', '최제우', '조선 철종'],
  },
  {
    id: '진주민란',
    type: '사건', kind: 'detail',
    title: '진주민란',
    description: '삼정 문란에 분노한 진주 농민 봉기 — 임술농민봉기의 시발점',
    startYear: 1862, endYear: 1862,
    difficulty: 3,
    era: '조선시대',
    tags: ['임술농민봉기', '조선 철종', '삼정 문란'],
  },
  {
    id: '삼정_문란',
    type: '제도', kind: 'detail',
    title: '삼정 문란',
    description: '세도정치기 전정·군정·환곡 등 조세 행정의 부패가 극에 달한 현상',
    startYear: 1800, endYear: 1862,
    difficulty: 3,
    era: '조선시대',
    tags: ['세도정치', '임술농민봉기', '조선 철종'],
  },

  // ===== 흥선대원군 detail =====
  {
    id: '사창제_시행',
    type: '제도', kind: 'detail',
    title: '사창제 시행',
    description: '흥선대원군이 환곡의 폐단을 해소하기 위해 마을 단위 곡식 대여 제도를 부활',
    startYear: 1867, endYear: 1867,
    difficulty: 4,
    era: '조선시대',
    tags: ['흥선대원군', '흥선대원군 집권'],
  },
  {
    id: '척화비_건립',
    type: '유물', kind: 'detail',
    title: '척화비 건립',
    description: '흥선대원군이 신미양요 후 전국에 세운 비석 — 통상 수교 거부 의지 표명',
    startYear: 1871, endYear: 1871,
    difficulty: 2,
    era: '조선시대',
    tags: ['흥선대원군', '신미양요', '통상수교거부'],
  },
  {
    id: '당백전_발행',
    type: '사건', kind: 'detail',
    title: '당백전 발행',
    description: '흥선대원군이 경복궁 중건 재원 마련을 위해 발행한 고액 화폐 — 인플레이션 초래',
    startYear: 1866, endYear: 1866,
    difficulty: 3,
    era: '조선시대',
    tags: ['흥선대원군', '경복궁 중건'],
  },
  {
    id: '대전회통_편찬',
    type: '사건', kind: 'detail',
    title: '대전회통 편찬',
    description: '흥선대원군 시기 대전통편 이후 변화를 반영한 조선 마지막 법전을 편찬',
    startYear: 1865, endYear: 1865,
    difficulty: 4,
    era: '조선시대',
    tags: ['흥선대원군', '흥선대원군 집권'],
  },

  // ===== 양요 detail =====
  {
    id: '외규장각_도서_약탈',
    type: '사건', kind: 'detail',
    title: '외규장각 도서 약탈',
    description: '병인양요 당시 프랑스군이 강화도 외규장각 도서 약 6천 권을 약탈',
    startYear: 1866, endYear: 1866,
    difficulty: 3,
    era: '조선시대',
    tags: ['병인양요', '조선 고종', '흥선대원군'],
  },
  {
    id: '양헌수_정족산성',
    type: '사건', kind: 'detail',
    title: '양헌수의 정족산성 승리',
    description: '병인양요 때 양헌수가 정족산성에서 프랑스군을 격퇴',
    startYear: 1866, endYear: 1866,
    difficulty: 4,
    era: '조선시대',
    tags: ['병인양요', '양헌수', '조선 고종'],
  },
  {
    id: '어재연_광성보',
    type: '사건', kind: 'detail',
    title: '어재연의 광성보 전투',
    description: '신미양요 때 어재연 부대가 광성보에서 미군에 맞서 분전 — 어재연 전사',
    startYear: 1871, endYear: 1871,
    difficulty: 3,
    era: '조선시대',
    tags: ['신미양요', '어재연', '조선 고종'],
  },
  {
    id: '제너럴셔먼호_사건',
    type: '사건', kind: 'detail',
    title: '제너럴셔먼호 사건',
    description: '대동강에 들어온 미국 상선 제너럴셔먼호가 평양 군민에 의해 격침된 사건 — 신미양요의 발단',
    startYear: 1866, endYear: 1866,
    difficulty: 4,
    era: '조선시대',
    tags: ['신미양요', '조선 고종', '흥선대원군'],
  },
];
