// 선사·고조선 디테일 손작성 — 자동생성 데이터의 거의 동일한 변형 반복 문제 보완용.
// 30개 (구석기 6 / 신석기 7 / 청동기 6 / 철기 5 / 고조선 6).
// 모든 tag는 KEYWORD_META에 등록된 기존 키워드만 참조 (구석기·신석기·청동기·철기 시대 / 고조선 / 명도전).

const PREHISTORIC_DETAILS = [
  // ===== 구석기 시대 =====
  {
    id: '구석기_이동생활',
    type: '사건', kind: 'detail',
    title: '구석기 이동 생활',
    description: '사냥감을 따라 무리지어 이동 생활을 하였다.',
    startYear: -100000, endYear: -10000,
    difficulty: 2, era: '선사시대',
    tags: ['구석기 시대'],
  },
  {
    id: '구석기_사냥채집',
    type: '사건', kind: 'detail',
    title: '구석기 사냥과 채집',
    description: '사냥과 채집을 통해 식량을 얻었다.',
    startYear: -100000, endYear: -10000,
    difficulty: 2, era: '선사시대',
    tags: ['구석기 시대'],
  },
  {
    id: '구석기_슴베찌르개',
    type: '사건', kind: 'detail',
    title: '슴베찌르개 사용',
    description: '슴베찌르개를 만들어 사냥에 사용하였다.',
    startYear: -40000, endYear: -10000,
    difficulty: 3, era: '선사시대',
    tags: ['구석기 시대'],
  },
  {
    id: '구석기_뼈뿔도구',
    type: '사건', kind: 'detail',
    title: '뼈·뿔 도구',
    description: '동물의 뼈와 뿔로 도구를 만들었다.',
    startYear: -100000, endYear: -10000,
    difficulty: 3, era: '선사시대',
    tags: ['구석기 시대'],
  },
  {
    id: '구석기_전곡리',
    type: '사건', kind: 'detail',
    title: '연천 전곡리',
    description: '연천 전곡리 유적에서 아슐리안형 주먹도끼가 발견되었다.',
    startYear: -300000, endYear: -100000,
    difficulty: 2, era: '선사시대',
    tags: ['구석기 시대'],
  },
  {
    id: '구석기_석장리',
    type: '사건', kind: 'detail',
    title: '공주 석장리',
    description: '공주 석장리에서 다양한 구석기 유물이 출토되었다.',
    startYear: -50000, endYear: -10000,
    difficulty: 3, era: '선사시대',
    tags: ['구석기 시대'],
  },

  // ===== 신석기 시대 =====
  {
    id: '신석기_농경시작',
    type: '사건', kind: 'detail',
    title: '신석기 농경 시작',
    description: '조·피·수수 등을 재배하며 농경 생활이 시작되었다.',
    startYear: -6000, endYear: -2000,
    difficulty: 2, era: '선사시대',
    tags: ['신석기 시대'],
  },
  {
    id: '신석기_빗살무늬토기',
    type: '사건', kind: 'detail',
    title: '빗살무늬토기',
    description: '빗살무늬토기를 만들어 음식을 저장하였다.',
    startYear: -6000, endYear: -2000,
    difficulty: 2, era: '선사시대',
    tags: ['신석기 시대'],
    frequency: 2
  },
  {
    id: '신석기_갈돌갈판',
    type: '사건', kind: 'detail',
    title: '갈돌·갈판',
    description: '갈돌과 갈판으로 곡식의 껍질을 벗기고 가루로 만들었다.',
    startYear: -6000, endYear: -2000,
    difficulty: 3, era: '선사시대',
    tags: ['신석기 시대'],
  },
  {
    id: '신석기_가락바퀴',
    type: '사건', kind: 'detail',
    title: '가락바퀴와 뼈바늘',
    description: '가락바퀴로 실을 뽑고 뼈바늘로 옷을 지어 입었다.',
    startYear: -6000, endYear: -2000,
    difficulty: 3, era: '선사시대',
    tags: ['신석기 시대'],
  },
  {
    id: '신석기_움집정착',
    type: '사건', kind: 'detail',
    title: '신석기 움집·정착',
    description: '움집을 짓고 강가에 마을을 이루며 정착 생활을 시작하였다.',
    startYear: -6000, endYear: -2000,
    difficulty: 2, era: '선사시대',
    tags: ['신석기 시대'],
  },
  {
    id: '신석기_암사동오산리',
    type: '사건', kind: 'detail',
    title: '암사동·오산리 유적',
    description: '서울 암사동, 양양 오산리, 부산 동삼동 등에서 신석기 유적이 발견된다.',
    startYear: -6000, endYear: -2000,
    difficulty: 3, era: '선사시대',
    tags: ['신석기 시대'],
  },
  {
    id: '신석기_조개가면',
    type: '사건', kind: 'detail',
    title: '조개껍데기 가면',
    description: '조개껍데기로 가면을 만드는 등 예술품과 치레걸이가 제작되었다.',
    startYear: -5000, endYear: -2000,
    difficulty: 4, era: '선사시대',
    tags: ['신석기 시대'],
  },

  // ===== 청동기 시대 =====
  {
    id: '청동기_벼농사',
    type: '사건', kind: 'detail',
    title: '청동기 벼농사',
    description: '벼농사가 시작되어 농업 생산력이 크게 증가하였다.',
    startYear: -1500, endYear: -500,
    difficulty: 2, era: '선사시대',
    tags: ['청동기 시대'],
  },
  {
    id: '청동기_비파형동검',
    type: '사건', kind: 'detail',
    title: '비파형 동검',
    description: '비파형 동검과 거친무늬 거울 등 청동 제품이 만들어졌다.',
    startYear: -1500, endYear: -500,
    difficulty: 2, era: '선사시대',
    tags: ['청동기 시대'],
  },
  {
    id: '청동기_반달돌칼',
    type: '사건', kind: 'detail',
    title: '반달 돌칼',
    description: '반달 돌칼을 사용하여 곡식의 이삭을 수확하였다.',
    startYear: -1500, endYear: -500,
    difficulty: 2, era: '선사시대',
    tags: ['청동기 시대'],
  },
  {
    id: '청동기_민무늬토기',
    type: '사건', kind: 'detail',
    title: '청동기 토기',
    description: '민무늬토기, 미송리식 토기, 붉은 간토기가 사용되었다.',
    startYear: -1500, endYear: -500,
    difficulty: 3, era: '선사시대',
    tags: ['청동기 시대'],
  },
  {
    id: '청동기_고인돌',
    type: '사건', kind: 'detail',
    title: '고인돌·돌널무덤',
    description: '지배자의 권위를 상징하는 고인돌과 돌널무덤이 축조되었다.',
    startYear: -1500, endYear: -500,
    difficulty: 2, era: '선사시대',
    tags: ['청동기 시대'],
  },
  {
    id: '청동기_계급군장',
    type: '사건', kind: 'detail',
    title: '청동기 계급·군장',
    description: '잉여 생산물로 사유 재산과 계급이 발생하고 군장이 등장하였다.',
    startYear: -1500, endYear: -500,
    difficulty: 3, era: '선사시대',
    tags: ['청동기 시대'],
  },

  // ===== 철기 시대 =====
  {
    id: '철기_세형동검',
    type: '사건', kind: 'detail',
    title: '세형동검과 잔무늬 거울',
    description: '한국식 동검인 세형동검과 잔무늬 거울이 제작되었다.',
    startYear: -500, endYear: 0,
    difficulty: 3, era: '선사시대',
    tags: ['철기 시대'],
  },
  {
    id: '철기_거푸집',
    type: '사건', kind: 'detail',
    title: '철기 거푸집',
    description: '거푸집을 사용하여 청동기와 철기를 직접 제작하였다.',
    startYear: -500, endYear: 0,
    difficulty: 3, era: '선사시대',
    tags: ['철기 시대'],
  },
  {
    id: '철기_명도전교역',
    type: '사건', kind: 'detail',
    title: '명도전 출토',
    description: '명도전과 반량전 등 중국 화폐가 출토되어 활발한 교역을 보여준다.',
    startYear: -300, endYear: 0,
    difficulty: 3, era: '선사시대',
    tags: ['철기 시대', '명도전'],
  },
  {
    id: '철기_다호리붓',
    type: '사건', kind: 'detail',
    title: '창원 다호리 붓',
    description: '창원 다호리 유적에서 붓이 출토되어 한자 사용을 짐작케 한다.',
    startYear: -100, endYear: 0,
    difficulty: 4, era: '선사시대',
    tags: ['철기 시대'],
  },
  {
    id: '철기_연맹왕국',
    type: '사건', kind: 'detail',
    title: '철기 연맹왕국 형성',
    description: '부여·옥저·동예·삼한 등 여러 연맹 왕국이 형성되었다.',
    startYear: -200, endYear: 0,
    difficulty: 2, era: '선사시대',
    tags: ['철기 시대'],
  },

  // ===== 고조선 =====
  {
    id: '고조선_단군건국',
    type: '사건', kind: 'detail',
    title: '단군 건국',
    description: '단군왕검이 기원전 2333년에 건국한 것으로 전해진다.',
    startYear: -2333, endYear: -2333,
    difficulty: 2, era: '고조선',
    tags: ['고조선'],
  },
  {
    id: '고조선_8조법',
    type: '사건', kind: 'detail',
    title: '범금 8조',
    description: '범금 8조를 만들어 사회 질서를 유지하였다.',
    startYear: -1000, endYear: -108,
    difficulty: 2, era: '고조선',
    tags: ['고조선'],
    frequency: 2
  },
  {
    id: '고조선_위만',
    type: '사건', kind: 'detail',
    title: '위만 집권',
    description: '기원전 194년 위만이 정변을 일으켜 왕이 되었다.',
    startYear: -194, endYear: -194,
    difficulty: 3, era: '고조선',
    tags: ['고조선'],
  },
  {
    id: '고조선_철기수용',
    type: '사건', kind: 'detail',
    title: '고조선 철기 수용',
    description: '위만 시기에 본격적으로 철기를 수용하여 영토를 확장하였다.',
    startYear: -194, endYear: -108,
    difficulty: 3, era: '고조선',
    tags: ['고조선'],
  },
  {
    id: '고조선_한무제멸망',
    type: '사건', kind: 'detail',
    title: '고조선 멸망',
    description: '기원전 108년 한 무제의 침공으로 멸망하였다.',
    startYear: -108, endYear: -108,
    difficulty: 2, era: '고조선',
    tags: ['고조선'],
  },
  {
    id: '고조선_문화권표지',
    type: '사건', kind: 'detail',
    title: '고조선 문화권',
    description: '비파형 동검과 미송리식 토기의 분포로 그 문화권을 짐작할 수 있다.',
    startYear: -1500, endYear: -500,
    difficulty: 3, era: '고조선',
    tags: ['고조선'],
  },

  // ===== 부여 (6) =====
  {
    id: '부여_송화강',
    type: '사건', kind: 'detail',
    title: '부여 송화강',
    description: '만주 송화강 유역에서 등장한 초기 국가이다.',
    startYear: -200, endYear: 494,
    difficulty: 2, era: '선사시대',
    tags: ['부여'],
  },
  {
    id: '부여_사출도',
    type: '사건', kind: 'detail',
    title: '부여 사출도',
    description: '마가·우가·저가·구가가 다스리는 사출도가 있었다.',
    startYear: -200, endYear: 494,
    difficulty: 2, era: '선사시대',
    tags: ['부여'],
  },
  {
    id: '부여_영고',
    type: '사건', kind: 'detail',
    title: '부여 영고',
    description: '12월에 영고라는 제천행사를 열었다.',
    startYear: -200, endYear: 494,
    difficulty: 2, era: '선사시대',
    tags: ['부여'],
    frequency: 3
  },
  {
    id: '부여_1책12법',
    type: '사건', kind: 'detail',
    title: '1책 12법',
    description: '도둑질한 자는 12배로 갚게 하는 1책 12법이 있었다.',
    startYear: -200, endYear: 494,
    difficulty: 2, era: '선사시대',
    tags: ['부여'],
  },
  {
    id: '부여_우제점법',
    type: '사건', kind: 'detail',
    title: '우제점법',
    description: '전쟁이 일어나면 소 발굽으로 길흉을 점치는 우제점법을 사용하였다.',
    startYear: -200, endYear: 494,
    difficulty: 3, era: '선사시대',
    tags: ['부여'],
  },
  {
    id: '부여_순장',
    type: '사건', kind: 'detail',
    title: '부여 순장',
    description: '왕이 죽으면 사람을 함께 묻는 순장 풍습이 있었다.',
    startYear: -200, endYear: 494,
    difficulty: 3, era: '선사시대',
    tags: ['부여'],
  },

  // ===== 옥저 (5) =====
  {
    id: '옥저_함흥평야',
    type: '사건', kind: 'detail',
    title: '옥저의 위치',
    description: '함경도 함흥평야 일대 동해안 북부에 자리잡았다.',
    startYear: -200, endYear: 285,
    difficulty: 3, era: '선사시대',
    tags: ['옥저'],
  },
  {
    id: '옥저_민며느리제',
    type: '사건', kind: 'detail',
    title: '민며느리제',
    description: '어린 여자아이를 데려와 키운 뒤 며느리로 삼는 민며느리제가 있었다.',
    startYear: -200, endYear: 285,
    difficulty: 2, era: '선사시대',
    tags: ['옥저'],
  },
  {
    id: '옥저_가족공동무덤',
    type: '사건', kind: 'detail',
    title: '가족공동무덤',
    description: '가족이 죽으면 한 무덤에 모아 묻는 가족공동무덤(골장제)을 사용하였다.',
    startYear: -200, endYear: 285,
    difficulty: 2, era: '선사시대',
    tags: ['옥저'],
  },
  {
    id: '옥저_읍군삼로',
    type: '사건', kind: 'detail',
    title: '옥저 군장',
    description: '읍군·삼로 등의 군장이 부족을 다스렸다.',
    startYear: -200, endYear: 285,
    difficulty: 4, era: '선사시대',
    tags: ['옥저'],
  },
  {
    id: '옥저_해산물공물',
    type: '사건', kind: 'detail',
    title: '옥저 공물',
    description: '해산물과 소금을 고구려에 공물로 바쳤다.',
    startYear: -200, endYear: 285,
    difficulty: 3, era: '선사시대',
    tags: ['옥저'],
  },

  // ===== 동예 (5) =====
  {
    id: '동예_강원북부',
    type: '사건', kind: 'detail',
    title: '동예 강원북부',
    description: '강원도 북부 동해안 중부 지역에 위치하였다.',
    startYear: -200, endYear: 313,
    difficulty: 3, era: '선사시대',
    tags: ['동예'],
  },
  {
    id: '동예_책화',
    type: '사건', kind: 'detail',
    title: '책화',
    description: '다른 부족의 영역을 침범하면 노예·가축으로 변상하는 책화가 있었다.',
    startYear: -200, endYear: 313,
    difficulty: 2, era: '선사시대',
    tags: ['동예'],
  },
  {
    id: '동예_족외혼',
    type: '사건', kind: 'detail',
    title: '동예 족외혼',
    description: '같은 씨족끼리는 혼인하지 않는 족외혼 풍습이 있었다.',
    startYear: -200, endYear: 313,
    difficulty: 3, era: '선사시대',
    tags: ['동예'],
  },
  {
    id: '동예_무천',
    type: '사건', kind: 'detail',
    title: '동예 무천',
    description: '10월에 무천이라는 제천행사를 열었다.',
    startYear: -200, endYear: 313,
    difficulty: 2, era: '선사시대',
    tags: ['동예'],
  },
  {
    id: '동예_특산물',
    type: '사건', kind: 'detail',
    title: '동예 특산물',
    description: '단궁·과하마·반어피 등이 특산물로 유명하였다.',
    startYear: -200, endYear: 313,
    difficulty: 3, era: '선사시대',
    tags: ['동예'],
  },

  // ===== 삼한 (4) =====
  {
    id: '삼한_세부족',
    type: '사건', kind: 'detail',
    title: '삼한 구성',
    description: '마한·진한·변한의 세 연맹체로 구성되었다.',
    startYear: -100, endYear: 300,
    difficulty: 2, era: '선사시대',
    tags: ['삼한'],
  },
  {
    id: '삼한_소도천군',
    type: '사건', kind: 'detail',
    title: '삼한 소도·천군',
    description: '천군이 다스리는 소도라는 신성 지역이 있어 정치와 종교가 분리되었다.',
    startYear: -100, endYear: 300,
    difficulty: 2, era: '선사시대',
    tags: ['삼한'],
  },
  {
    id: '삼한_계절제',
    type: '사건', kind: 'detail',
    title: '삼한 계절제',
    description: '5월과 10월에 계절제를 열어 농경의 시작과 추수를 기념하였다.',
    startYear: -100, endYear: 300,
    difficulty: 3, era: '선사시대',
    tags: ['삼한'],
  },
  {
    id: '삼한_변한철',
    type: '사건', kind: 'detail',
    title: '변한 철 수출',
    description: '변한 지역은 철이 풍부하여 낙랑·왜에 수출하였다.',
    startYear: -100, endYear: 300,
    difficulty: 3, era: '선사시대',
    tags: ['삼한'],
  },
];
